name: Full release
on:
  push:
    branches:
    - master
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Test with dotnet
      run: dotnet test
        
    - name: Build with dotnet
      run: dotnet pack --configuration Release -o out /p:Version=1.2.0.${{github.run_number}}
      
    - name: Push nuget package
      run: dotnet nuget push ./out/*.nupkg -k ${{ secrets.Nuget_Key }} -s https://api.nuget.org/v3/index.json
